### ISSUE TITLE
idea: radial menu sub menus

### ISSUE THREAD

**Issue by GeneralMidi** [dumbeau/AutoHotPie#15]
hey, I messed around with Radial Menu v4 for a while, but just couldn't get into it. Such an old fashioned feel to the interface. Yours is so much better, I'm already constantly using it. 

One thing I did really like about Radial Menu though is the way it explodes out sub menus. It doesn't lose the base layer, everything is still visible and it's easy to close the submenu and reach for something else. Left clicking on a submenu opens it, left clicking again closes only the sub menu.

Do you think something like this might be possible with AutoHotPie? 

![radia](https://user-images.githubusercontent.com/47597511/145672118-2c7093fc-0015-4843-b12a-feba88e93c27.gif)

**Comment by dumbeau** [comment]
I remember radial menu!  Yeah I remember trying it before I started working on this but I just didn't like it as my main inspiration came from blender pie menus.  So the only relevant thing I have currently is the 'Include Previous Menu Function' switch which adds the 'Back' slice.  This way the means of going back to a base menu is always going back the direction you came.
![image](https://user-images.githubusercontent.com/36665762/145694926-ad96e215-3850-4884-b17e-efaf559a3ca1.png)

This does miss out on having a visual for the base menu.  I'm open to ideas there.  First thing that comes to mind is just having the base menu's circle remain on screen without their labels, just so going back to those menus is easier to gauge the mouse movement.

**Comment by GeneralMidi** [comment]
Thanks for your comments. Yes, the back button is helpful, I hadn't seen that yet. Hrmm, I think something could be more helpful here too with a visual for the base menu...but I'm not so sure at this stage. I'll play some more. Maybe could tie in with the background blur idea...not sure...

**Comment by GeneralMidi** [comment]
Ok, I hope you're prepared to be astounded by some other-worldly gif creation skills...

Here are some very rough ideas. What do you think? 

In this one, it's a little like holding off from commitment. I can see where I came from, and where I will go to should I commit. 

![one](https://user-images.githubusercontent.com/47597511/145988488-6c36eeef-fd6a-46d4-8196-4ddb82132219.gif)

And in this one, you can see the user has committed. As far as inspiration goes, I reached the end of my skill levels on this one! 

But hopefully it might have inspired you. It just feels a little abrupt going into sub menu. 

![two](https://user-images.githubusercontent.com/47597511/145988659-9c6bda6c-eebd-432c-a5ad-6099ee1f7fa5.gif)

I hope you don't mind these ideas, I just really love this app/software/script - it's so incredibly cool! But appreciate it might not be in your vision for it. No worries at all, take it or leave it.

Oh, just had a thought...or you could maybe using the blurring idea to keep the base menu visible but blurred, and have the current sub menu un-blurred...dunno, just ideas. 

cheers

**Comment by dumbeau** [comment]
I'm honored!  Happy you like my niche of putting circles on people's screens.  I like your latter gif, I think I'll try to get it working that way if the user has the back function enabled.  This allows for a more confident mouse movement back to the original menu without overshooting.  I tried getting the blur or shadow to work, but the gdip library (what I'm using to draw overlays) can be an ordeal to work around with without slowing the application down, so that is something that I'm putting on the backburner for now.

The first gif would be good for exploration, but I'm thinking that the label slice should be enough.  If a user can't understand what's going to be in the submenu based on the label, the best solution would probably just be a better slice label/icon.

Many of the features in this are user requested at this point or at least based on user requests, so I'm always happy to consider new ideas 👍, especially while my audience is so small that I can actually message everyone back.

**Comment by GeneralMidi** [comment]
Haha, that's awesome. Thanks again for considering new ideas.

What about cheating with the blur? I mean, I'm not sure if it's possible ,
but could you maybe put like an image with 50% alpha or something
under-layed that's a touch bigger than the menu item to fake the blur?

**Comment by dumbeau** [comment]
Gdip has a blur function, but it can only be applied to an entire bitmap.  The tricky part is just getting a second bitmap to overlay for some reason.  I like this route because then I can just draw the same pie menu visual with the same logic and just set colors to black and 50% alpha, and apply the blur.

**Comment by rostder** [comment]
Hey, @GeneralMidi!
 I really like your feature with the Radial Menu, but unfortunately, I don`t have enough programming skills to reproduce something similar. I will be very appreciative if you share your work and then I will give you my feedback on using it.
 Thank you for your efforts and all the best!

**Comment by GeneralMidi** [comment]
Um, I'm confused. I'm not the developer. It was just a very crude  idea of something I had in my head. I'm not sure how else I can help you.

**Comment by dumbeau** [comment]
@rostder source code is available and you can download the installer in the [releases](https://github.com/dumbeau/AutoHotPie/releases) section.
