### ISSUE TITLE
[possible bug][feature request] Give me a slice back

### ISSUE THREAD

**Issue by vfxturjo** [dumbeau/AutoHotPie#36]
![image](https://user-images.githubusercontent.com/44445014/157736232-db7fd453-4e05-4218-abb6-ebe4239ca362.png)
typical day starts...

![image](https://user-images.githubusercontent.com/44445014/157736545-400397cd-c7b9-4983-82d4-3e22a5d8c0f7.png)
then one starts to remove the slices
one by one...
...
![image](https://user-images.githubusercontent.com/44445014/157736637-7443772a-6cf5-4427-8516-ae4e8517cc18.png)
...

...
![image](https://user-images.githubusercontent.com/44445014/157736731-1adb22d1-ad12-4c99-a7f5-217cc6a25288.png)
...

...
![image](https://user-images.githubusercontent.com/44445014/157736780-0c528207-106b-4b2c-895a-bf1e92055ef2.png)
...

then...
![image](https://user-images.githubusercontent.com/44445014/157736849-08de6005-1d48-4fa0-bff5-f7c789ba274c.png)
no way to get a slice back :(
help!

**Comment by vfxturjo** [comment]
I tried to make a screenshot story, not to offend you in any way... 
it is just for fun. I love tinkering with AHPie so much and I respect you

**Comment by dumbeau** [comment]
This is intentional, as it provides a proper punishment for taking the last slice (seriously who takes the last slice!??)... lol

I knew it was a matter of time until somebody would be willing to stress test the UI into submission, and I know for a fact there are still issues like this somewhere.  I may hide easter eggs in these places.  This is fixed in v1.0.17, I just replaced the exe.

No worries you won't offend me, and I respect you and the effort you've put into this too!
