### ISSUE TITLE
[feature request] Add font weight setting

### ISSUE THREAD

**Issue by Kyuhunter** [dumbeau/AutoHotPie#45]
As the title says, a font-weight Setting for the menus would be great. I am using a 4k monitor and the text is very slim.
![AutoHotPie](https://user-images.githubusercontent.com/44449951/163067483-7a09522b-5471-40a1-b6fe-3bad0a0f5371.png)
The Picture is taken with Font Roboto and font-size 18.

**Comment by dumbeau** [comment]
Got it, I will add this.

Temporary fix for now, you can export the settings file, open it and on line 15 you'll see 
`"font": "YourSelectedFont"`
Change "YourSelectedFont" to your actual font, the settings UI will use Times, but the pie menus will use your selected font when being used.  Otherwise I'm thinking I'll have this fixed this weekend.

**Comment by dumbeau** [comment]
Fonts and all of their weights now appear in the font dropdown in [v1.0.18](https://github.com/dumbeau/AutoHotPie/releases).
![image](https://user-images.githubusercontent.com/36665762/167462831-8f711552-0584-4a55-84c7-966ccab770ae.png)
