### ISSUE TITLE
[Bug] Slice hotkey not functioning properly when using [Click on Selection] mode

### ISSUE THREAD

**Issue by picklepissjar** [dumbeau/AutoHotPie#74]
Win10 Home   21H1  19043.2130
v1.0.24.0
Action: Using a slice hotkey when in [Click on Selection] Activation Mode
Result: The hotkey is "stuck" and is continuously being sent to the pie menu upon pressing the pie key.
Kept getting stuck in sub-menus, but it turns out the behavior applies to other slices as well.
Love the project btw :)

**Comment by dumbeau** [comment]
I saw the name "picklepissjar" and knew immediately that this issue was coming from a technically literate user and had to be addressed (also this issue happened to be easy).

This should now be fixed in [v1.0.25](https://github.com/dumbeau/AutoHotPie/releases).  Can you confirm that it works on your end?

**Comment by picklepissjar** [comment]
It's working on my end. 👍
