### ISSUE TITLE
Pie Enable Key doesn't work and some feature requests

### ISSUE THREAD

**Issue by rexelbartolome** [dumbeau/AutoHotPie#9]
Both the toggle and hold version for enabling the Pie Menu don't work, also would like some sort of pop up or notification what state a Pie Menu is on when the Enable Pie Key is pressed if that's alright :D

Also thought of a bunch of UX things

When adding a `Function` to a `Slice`, after clicking `Send Key` on the dropdown, you can make it go straight to the **Press a Key** screen, instead of having to click `Assign Key` button before the **Press a Key** comes up. Same goes for the `Run File` function.

When adding a new pie menu, clicking `Add Pie Menu` button doesn't notify you if you haven't assigned a Keystroke for the pie menu yet. So I thought it just didn't work for some reason 😅

**Comment by dumbeau** [comment]
> Both the toggle and hold version for enabling the Pie Menu don't work, also would like some sort of pop up or notification what state a Pie Menu is on when the Enable Pie Key is pressed if that's alright :D

Ope, yikes yeah I'll fix that.  As for the overlay notification, that's a good idea.  I would want to make this very small overlay in the bottom right of the screen the mouse is on and only use it for if the Pie Enable Key is set to toggle.
Off the top of my head maybe something like this?  Open to ideas here, looking for something unobtrusive.
![image](https://user-images.githubusercontent.com/36665762/141930815-9aef0d6c-00ad-4984-8a7c-64966a94342e.png)

I feel like the overlay would get annoying if somebody is using the 'Hold' mode.  Do you think it would be necessary for the Hold mode?  Seems like it might be helpful to see at first but could get annoying later, and just having the key pressed is enough.

> When adding a `Function` to a `Slice`, after clicking `Send Key` on the dropdown, you can make it go straight to the **Press a Key** screen, instead of having to click `Assign Key` button before the **Press a Key** comes up. Same goes for the `Run File` function.

This will be added for 'Send Key', 'Run File' and 'Open Folder'.

> When adding a new pie menu, clicking `Add Pie Menu` button doesn't notify you if you haven't assigned a Keystroke for the pie menu yet. So I thought it just didn't work for some reason 😅

I considered doing this, and then I decided I'll come back to it and just forgot about it.  There are a few places I need to add data validation warnings.  Not even difficult to do, I just got lazy on that one 😅.   Thanks again for finding my bugs and for the good suggestions!

**Comment by dumbeau** [comment]
'Pie Enable Key' is partially fixed in v1.0.8 at the moment.

There is an issue with Pie Menus locking up and blocking LButton when aggressively tapping the pie enable key with pie menu hotkeys that have Ctrl or Alt as a modifier (Shift seems fine).  You have to Ctrl+Shift+Esc for task manager and force close PieMenu.exe if it ever happens.  But I won't be able to work on this again until later this week so I just wanted to get the pie enable keys functional quick.

**Comment by rexelbartolome** [comment]
Great! And yea it's alright, I don't use the Pie Enable feature very often so I'm fine with waiting.

> Off the top of my head maybe something like this? Open to ideas here, looking for something unobtrusive.
Yeah I think that's great. And I'm assuming the `Pie Menus` will be replaced by the Pie Menu name? Or is that for a global enable/disable?

I don't think it needs to be seen on Hold mode, as I think Hold mode kind of caters more to advanced/super users compared to Toggle anyway.

And you're welcome! 😊

**Comment by rexelbartolome** [comment]
> There is an issue with Pie Menus locking up and blocking LButton when aggressively tapping the pie enable key with pie menu hotkeys that have Ctrl or Alt as a modifier (Shift and keys without other modifiers seem fine). 

For some reason this issue also happens when you use explorer.exe as an assigned program for one of the profiles. I have the pie enable key assigned to 0 with no modifier keys and when I run it, it becomes blocked when I try to open the profile's pie menu. 

Also I found out that right click is still usable when blocked, and when you right click autohotpie on the system tray, you get to left click one of the options. So no opening of task manager necessary :D

**Comment by dumbeau** [comment]
Nice, I did put up some updates that I think fixed the locking up issue, so feel free to give it a try.  explorer.exe is kind of a special case application when it comes to sensing it. I'll look into that though, because I'm sure that's going to be a common desired profile.

**Comment by dumbeau** [comment]
All of these feature requests have been added and LMB locking has been fixed in [v1.0.10](https://github.com/dumbeau/AutoHotPie/releases).

- Pie Menus won't break on the assigned profile 'explorer.exe'
- Input data validation warnings have been added.
- 'Send Key', 'Run File' and 'Open Folder' now go to their relevant dialog after selection.
- An overlay notification has been added that shows the 'Pie Enable State' on the bottom right of the active monitor when the 'Pie Enable Key' is pressed when set to 'toggle'.
![image](https://user-images.githubusercontent.com/36665762/142899070-1a7c8a9e-20a6-4833-a217-deffe7505c34.png)
![image](https://user-images.githubusercontent.com/36665762/142899080-17254395-1037-4b88-8190-b81cf9875fc5.png)

As always, feel free to give feedback on these changes or reopen if you find a problem.
